### PR TITLE
basic design for backup

### PR DESCRIPTION
**Pull request by streetycat**

### CODE REVIEW

**Comment by waterflier** [comment]
Our goal is to design a scalable, Zero Dependence, and Zero Trust backup service. I believe we need to reflect the following aspects in the design:

- **High Performance**: I envision the following key metrics:
  - The amount of temporary space required during the backup process (a hard requirement, as insufficient space will prevent the backup from completing).
  - The less data generated by the backup, the better, which implicitly includes the need for "deduplication" or "incremental" backups.
  - The backup process is typically time-consuming, so we aim to minimize CPU/memory/disk usage during the backup process as much as possible.

- **Scalable Backup Targets**: This means we need to define some general "backup target protocols". I have considered at least the following types (additional suggestions are welcome):
  - **Sealed Sectors** (similar to the old method of backing up onto optical discs), where the backup result is immutable, and the backup operation has a clear historical record. This is the simplest type, and the DMC backup network operates this way.
  - **Directory Synchronization** (both HTTP DAV and rsync fall into this category), where the backup target is a regular directory. If this directory is writable, it may introduce some synchronization strategy issues. To support historical records, the underlying system of the target directory typically needs to provide support. This type of backup involves one-way synchronization (from source to target), which is simpler than two-way synchronization.

- **Extensible Backup Sources**: For example, during a long-running backup task, is the backup source writable? If the backup source is a directory that supports snapshot functionality, the actual source for the backup task is the snapshot created at the start of the backup. Managing the snapshot during the backup process reflects the backup system's understanding of the backup source.

In terms of flowchart design, I would like to highlight the following key features:

1. **Backup Task Management**
2. The key stages of a backup task: **Backup Source Preparation, Backup Target Preparation, Backup Data Preparation, and Backup Data Transfer to the Backup Target**. How can we design a process framework that allows us to implement a "prepare-while-transferring" logic that performs optimally in a scalable environment?
3. **Backup Target Management**, especially considering that some targets may involve subscription management.

**Comment by streetycat** [comment]
> Our goal is to design a scalable, Zero Dependence, and Zero Trust backup service. I believe we need to reflect the following aspects in the design:
> 
> * **High Performance**: I envision the following key metrics:
>   
>   * The amount of temporary space required during the backup process (a hard requirement, as insufficient space will prevent the backup from completing).
>   * The less data generated by the backup, the better, which implicitly includes the need for "deduplication" or "incremental" backups.
>   * The backup process is typically time-consuming, so we aim to minimize CPU/memory/disk usage during the backup process as much as possible.
> * **Scalable Backup Targets**: This means we need to define some general "backup target protocols". I have considered at least the following types (additional suggestions are welcome):
>   
>   * **Sealed Sectors** (similar to the old method of backing up onto optical discs), where the backup result is immutable, and the backup operation has a clear historical record. This is the simplest type, and the DMC backup network operates this way.
>   * **Directory Synchronization** (both HTTP DAV and rsync fall into this category), where the backup target is a regular directory. If this directory is writable, it may introduce some synchronization strategy issues. To support historical records, the underlying system of the target directory typically needs to provide support. This type of backup involves one-way synchronization (from source to target), which is simpler than two-way synchronization.
> * **Extensible Backup Sources**: For example, during a long-running backup task, is the backup source writable? If the backup source is a directory that supports snapshot functionality, the actual source for the backup task is the snapshot created at the start of the backup. Managing the snapshot during the backup process reflects the backup system's understanding of the backup source.
> 
> In terms of flowchart design, I would like to highlight the following key features:
> 
> 1. **Backup Task Management**
> 2. The key stages of a backup task: **Backup Source Preparation, Backup Target Preparation, Backup Data Preparation, and Backup Data Transfer to the Backup Target**. How can we design a process framework that allows us to implement a "prepare-while-transferring" logic that performs optimally in a scalable environment?
> 3. **Backup Target Management**, especially considering that some targets may involve subscription management.

1. In this design, I have abstracted the data source as `input` and the backup target as `output`, connecting them into a data flow through the `engine` module. This approach supports the expansion of various data sources and storage services:
    * The same storage service can act as either `input` or `output` depending on the backup requirements.
    * A storage service only needs to implement the interfaces reserved for `input` or `output` to fulfill the corresponding backup requirements.

2. I have added a simple process for preparing the backup data source, primarily supporting file system snapshots. Users are encouraged to use file systems that support snapshots. For users with file systems that do not support snapshots, support is temporarily unavailable, or only read-only mode is provided.

3. Backup data is read only during the actual upload process, reducing the consumption of temporary storage space. This is reflected in the flowchart.

4. `Zero Dependence, and Zero Trust` is provided by the specific `output` (storage service), which for now might be `DMC`.

5. Currently, this is a relatively rough process design. More detailed designs for each module and various data storage formats will be added later.

**Comment by waterflier** [comment]
I have read the document you recently submitted, and I have some questions about the working logic of the Engine you envisioned. I think we should describe the core process more precisely.

(From a dependency perspective, I assume the Engine depends on Input and Output. In terms of terminology, I still recommend using *Backup Source* and *Backup Target*.)

```javascript
function engine.run_task(backup_task) {
  input = backup_task.input;
  output = backup_task.output;

  // Engine main logic:
  while(input.has_more_files()) { 
    tmpfiles = input.prepare_for(output.target_type)
    for (tmpfile in tmpfiles) {
      out_tmp = output.process(tmpfile)
      output.upload(out_tmp)
      delete_file(out_tmp)
    }
    input.set_backup_ok(tmpfiles, OK)
  }
}
```

Next, let’s consider the first implementation of `input` and `output`. Specifically, how we can identify potential issues through a minimal implementation (for example, where the source is a `local directory` and the target is an `rsync directory`).

**Comment by streetycat** [comment]
> I have read the document you recently submitted, and I have some questions about the working logic of the Engine you envisioned. I think we should describe the core process more precisely.
> 
> (From a dependency perspective, I assume the Engine depends on Input and Output. In terms of terminology, I still recommend using _Backup Source_ and _Backup Target_.)
> 
> ```js
> function engine.run_task(backup_task) {
>   input = backup_task.input;
>   output = backup_task.output;
> 
>   // Engine main logic:
>   while(input.has_more_files()) { 
>     tmpfiles = input.prepare_for(output.target_type)
>     for (tmpfile in tmpfiles) {
>       out_tmp = output.process(tmpfile)
>       output.upload(out_tmp)
>       delete_file(out_tmp)
>     }
>     input.set_backup_ok(tmpfiles, OK)
>   }
> }
> ```
> 
> Next, let’s consider the first implementation of and . Specifically, how we can identify potential issues through a minimal implementation (for example, where the source is a and the target is an ).`input``output``local directory``rsync directory`


This document aims to describe the data flow and the relationships between several modules. I will continue to submit more detailed and accurate flowcharts, pseudo-code, and data formats (packaging format and indexing, etc.).

I have abstracted the backup source and target as `input` and `output` because this architecture is suitable for any storage scenario, not just for `backup`. However, since `backup` is the most conceivable primary scenario, I support the suggestion to name them `Backup Source` and `Backup Target` to unify the terminology.

**Comment by streetycat** [comment]
In the previous documentation, the inter-module communication protocol was not specified. I have now added this information. I propose using the HTTP protocol to decouple the modules, which will enhance both scalability and stability.

**Comment by streetycat** [comment]
The `backup` module has been separated into its own project. We will use [this issue](https://github.com/buckyos/bucky_backup_suite/pull/1) to continue the discussion on the design and implementation of the backup module.

**Pull request closed without merging**
